### ISSUE TITLE
Exception creating requirements file

### ISSUE THREAD

**Issue by zbateson** [armenak/DataDefender#44]
Hi @armenak 

This is the error I was receiving when trying to create a requirements file from data discovery.  Note this only happens when using -R -- without it, I get the list of columns without an error.

Parameters/options passed:

``` java -jar DataDefender.jar discover -d -r -R output.xml ```

Error:

``` 
Exception in thread "main" com.strider.dataanonymizer.AnonymizerException: No matches to create requirement from!
	at com.strider.dataanonymizer.Discoverer.createRequirement(Discoverer.java:37)
	at com.strider.dataanonymizer.Anonymizer.main(Anonymizer.java:114)
```

If I have some time I'll take a look myself.  Please let me know if you want any more details.

Thanks,
Zaahid

**Comment by armenak** [comment]
Hi @zbateson,
This bug is fixed. Thanks for finding it.
Thanks,
Armenak
