### ISSUE TITLE
FileDiscovery - Failed if directory contains other subdirectories inside

### ISSUE THREAD

**Issue by lcmarques** [armenak/DataDefender#81]
Analyzing /Volumes/TestSecurity-2/Subfolder
Extension
Exception in thread "main" java.io.FileNotFoundException: /Volumes/TestSecurity-2/Subfolder (Is a directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.strider.datadefender.FileDiscoverer.discoverAgainstSingleModel(FileDiscoverer.java:134)
	at com.strider.datadefender.FileDiscoverer.discover(FileDiscoverer.java:79)
	at com.strider.datadefender.DataDefender.main(DataDefender.java:103)

**Comment by lcmarques** [comment]
Here is the patch. It basically ignores the subdirectory or any other I/O error and continues. Not sure if it is the best approach but at least does not fail.
Also, a message is returned saying the file/dir will be ignored.

[patch_subdirectories_filediscovery.txt](https://github.com/armenak/DataDefender/files/1152881/patch_subdirectories_filediscovery.txt)

**Comment by armenak** [comment]
Thank you. Can you please send the pull request?

**Comment by lcmarques** [comment]
It seems that i need to fork it to send you the pull request right? Thanks
