### ISSUE TITLE
Error running jar -jar DataDefender.jar --help

### ISSUE THREAD

**Issue by marciahon29** [armenak/DataDefender#93]
Please let me know how to solve this error:

$ java -jar DataDefender.jar --help
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/strider/datadefender/DataDefender : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: com.strider.datadefender.DataDefender. Program will exit.

**Comment by armenak** [comment]
Thank you for letting me know.
